module.exports = [
  {
    service_id: 1,
    name: 'Google Trends RSS US',
    full_url: 'https://trends.google.com/trending/rss?geo=US',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'en',
    language_name: 'English',
    country_code: 'US',
    country_name: 'United States',
    service_status_id: 1,
  },
  {
    service_id: 2,
    name: 'Google Trends RSS CN',
    full_url: 'https://trends.google.com/trending/rss?geo=CN',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'zh',
    language_name: 'Chinese',
    country_code: 'CN',
    country_name: 'China',
    service_status_id: 2,
  },
  {
    service_id: 3,
    name: 'Google Trends RSS JP',
    full_url: 'https://trends.google.com/trending/rss?geo=JP',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'ja',
    language_name: 'Japanese',
    country_code: 'JP',
    country_name: 'Japan',
    service_status_id: 1,
  },
  {
    service_id: 4,
    name: 'Google Trends RSS KR',
    full_url: 'https://trends.google.com/trending/rss?geo=KR',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'ko',
    language_name: 'Korean',
    country_code: 'KR',
    country_name: 'Korea, Republic of',
    service_status_id: 1,
  },
  {
    service_id: 5,
    name: 'Google Trends RSS IN',
    full_url: 'https://trends.google.com/trending/rss?geo=IN',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'hi',
    language_name: 'Hindi',
    country_code: 'IN',
    country_name: 'India',
    service_status_id: 1,
  },
  {
    service_id: 6,
    name: 'Google Trends RSS BR',
    full_url: 'https://trends.google.com/trending/rss?geo=BR',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'pt',
    language_name: 'Portuguese',
    country_code: 'BR',
    country_name: 'Brazil',
    service_status_id: 1,
  },
  {
    service_id: 7,
    name: 'Google Trends RSS DE',
    full_url: 'https://trends.google.com/trending/rss?geo=DE',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'de',
    language_name: 'German',
    country_code: 'DE',
    country_name: 'Germany',
    service_status_id: 1,
  },
  {
    service_id: 8,
    name: 'Google Trends RSS GB',
    full_url: 'https://trends.google.com/trending/rss?geo=GB',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'en',
    language_name: 'English',
    country_code: 'GB',
    country_name: 'United Kingdom',
    service_status_id: 1,
  },
  {
    service_id: 9,
    name: 'Google Trends RSS FR',
    full_url: 'https://trends.google.com/trending/rss?geo=FR',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'fr',
    language_name: 'French',
    country_code: 'FR',
    country_name: 'France',
    service_status_id: 1,
  },
  {
    service_id: 10,
    name: 'Google Trends RSS RU',
    full_url: 'https://trends.google.com/trending/rss?geo=RU',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'ru',
    language_name: 'Russian',
    country_code: 'RU',
    country_name: 'Russian Federation',
    service_status_id: 1,
  },
  {
    service_id: 11,
    name: 'Google Trends RSS AU',
    full_url: 'https://trends.google.com/trending/rss?geo=AU',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'en',
    language_name: 'English',
    country_code: 'AU',
    country_name: 'Australia',
    service_status_id: 1,
  },
  {
    service_id: 12,
    name: 'Google Trends RSS TR',
    full_url: 'https://trends.google.com/trending/rss?geo=TR',
    access_type_id: 2,
    data_format_code: 'xml',
    fetch_frequency: 300,
    rate_limit: 60,
    timeout: 30,
    language_code: 'tr',
    language_name: 'Turkish',
    country_code: 'TR',
    country_name: 'Turkey',
    service_status_id: 1,
  }
];
